// ===================== SAMPLE LISTINGS DATA =====================
const SAMPLE_LISTINGS = [
  {
    id: 1001, sellerId: 'razeking@example.com', sellerName: 'RazeKing', sellerRep: 4.8,
    title: 'Radiant Account | 67 Skins | AP Server | Champions Vandal',
    price: 28000, region: 'AP',
    rank: 'Radiant', peakRank: 'Radiant',
    level: 312, skinCount: 67, agentsCount: 23,
    emailAccess: true, banHistory: false, banDetail: '',
    limited: true, limitedDetail: 'Champions 2022 Vandal, VCT 2023 Phantom',
    vpBalance: 450, bpCompleted: 14,
    collections: ['Reaver', 'Prime', 'Champions', 'Elderflame'],
    skinTags: ['Reaver Vandal', 'Prime Phantom', 'Champions 2022 Vandal', 'Elderflame Operator'],
    agents: ['Jett','Reyna','Sage','Sova','Killjoy','Omen','Viper','Breach','Phoenix','Skye','Fade','Gekko','Neon','Raze','Chamber','Cypher','Harbor','Astra','KAY/O','Yoru','Iso','Clove','Deadlock'],
    images: [],
    aiSummary: 'Radiant account with 67 skins including Champions 2022 Vandal and VCT Phantom. AP server, original email included. ₹28,000.',
    tags: ['#Radiant','#67Skins','#APServer','#EmailIncluded','#NoBanHistory','#LimitedSkins','#ReaverCollection','#ChampionsCollection','#ReaverVandal'],
    accountHistory: 'Self-leveled from day 1, played since Closed Beta. Never sold before.',
    vouchHistory: '5 vouches on Sythe.org',
    createdAt: new Date(Date.now() - 2*24*3600*1000).toISOString(),
    status: 'active', views: 247, contactReveals: 38, saves: 19, isGem: false
  },
  {
    id: 1002, sellerId: 'skyemain@example.com', sellerName: 'SkyeMain', sellerRep: 4.2,
    title: 'Immortal 3 Account | 43 Skins | AP | Prime + Glitchpop',
    price: 9500, region: 'AP',
    rank: 'Immortal 3', peakRank: 'Immortal 3',
    level: 198, skinCount: 43, agentsCount: 18,
    emailAccess: true, banHistory: false, banDetail: '',
    limited: false, limitedDetail: '',
    vpBalance: 0, bpCompleted: 9,
    collections: ['Prime', 'Glitchpop', 'RGX'],
    skinTags: ['Prime Phantom', 'Glitchpop Vandal', 'RGX 11z Pro Vandal'],
    agents: ['Jett','Reyna','Sage','Sova','Killjoy','Omen','Viper','Breach','Phoenix','Skye','Neon','Raze','Chamber','Cypher','Astra','KAY/O','Iso','Fade'],
    images: [],
    aiSummary: 'Immortal 3 account with 43 skins. AP server, email included. Prime, Glitchpop and RGX collections. ₹9,500.',
    tags: ['#Immortal3','#43Skins','#APServer','#EmailIncluded','#NoBanHistory','#PrimeCollection','#GlitchpopCollection','#PrimePhantom'],
    accountHistory: 'Owned for 1.5 years, self-leveled.',
    vouchHistory: 'No previous sales',
    createdAt: new Date(Date.now() - 5*24*3600*1000).toISOString(),
    status: 'active', views: 89, contactReveals: 12, saves: 7, isGem: false
  },
  {
    id: 1003, sellerId: 'diamonddave@example.com', sellerName: 'DiamondDave', sellerRep: 3.9,
    title: 'Diamond 2 Account | 28 Skins | NA Server | Elderflame Op',
    price: 5800, region: 'NA',
    rank: 'Diamond 2', peakRank: 'Diamond 3',
    level: 145, skinCount: 28, agentsCount: 15,
    emailAccess: false, banHistory: false, banDetail: '',
    limited: false, limitedDetail: '',
    vpBalance: 200, bpCompleted: 6,
    collections: ['Elderflame', 'Oni'],
    skinTags: ['Elderflame Operator', 'Oni Phantom'],
    agents: ['Jett','Reyna','Sage','Sova','Killjoy','Omen','Viper','Breach','Phoenix','Skye','Neon','Raze','Chamber','Cypher','Astra'],
    images: [],
    aiSummary: 'Diamond 2 account (peak D3) with 28 skins. AP server, credentials only. 200 VP remaining. Elderflame and Oni collections. ₹5,800.',
    tags: ['#Diamond2','#28Skins','#NAServer','#NoBanHistory','#200VP','#ElderflameCollection','#OniCollection','#ElderflameOperator'],
    accountHistory: 'Purchased 8 months ago, upgraded rank from Plat. Clean history.',
    vouchHistory: '2 vouches on Discord TradingHub',
    createdAt: new Date(Date.now() - 1*24*3600*1000).toISOString(),
    status: 'active', views: 134, contactReveals: 21, saves: 11, isGem: true
  },
  {
    id: 1004, sellerId: 'platkingvendor@sample.com', sellerName: 'PlatKing99', sellerRep: 4.0,
    title: '💎 HIDDEN GEM — Platinum 3 | 52 Skins | AP | Sentinels Bundle',
    price: 4200, region: 'AP',
    rank: 'Platinum 3', peakRank: 'Diamond 1',
    level: 220, skinCount: 52, agentsCount: 20,
    emailAccess: true, banHistory: false, banDetail: '',
    limited: true, limitedDetail: 'Sentinels of Light Vandal, Champions 2021 Vandal',
    vpBalance: 100, bpCompleted: 11,
    collections: ['Sentinels', 'Champions', 'Prime'],
    skinTags: ['Sentinels of Light Vandal', 'Champions 2021 Vandal', 'Prime Operator'],
    agents: ['Jett','Reyna','Sage','Sova','Killjoy','Omen','Viper','Breach','Phoenix','Skye','Fade','Neon','Raze','Chamber','Cypher','Astra','KAY/O','Yoru','Clove','Harbor'],
    images: [],
    aiSummary: 'Platinum 3 account (peak Diamond 1) with 52 skins including Sentinels of Light and Champions 2021 Vandal. AP server, email included. Exceptional value at ₹4,200.',
    tags: ['#Platinum3','#52Skins','#APServer','#EmailIncluded','#NoBanHistory','#LimitedSkins','#SentinelsCollection','#ChampionsCollection','#HiddenGem'],
    accountHistory: 'Self-leveled for 3 years. Stopped playing ranked, want to sell.',
    vouchHistory: '1 vouch on Sythe',
    createdAt: new Date(Date.now() - 3*24*3600*1000).toISOString(),
    status: 'active', views: 312, contactReveals: 67, saves: 44, isGem: true
  },
  {
    id: 1005, sellerId: 'eufraggervendor@sample.com', sellerName: 'EU_Fragger', sellerRep: 4.5,
    title: 'Ascendant 2 | 35 Skins | EU Server | Forsaken + Protocol',
    price: 7200, region: 'EU',
    rank: 'Ascendant 2', peakRank: 'Immortal 1',
    level: 178, skinCount: 35, agentsCount: 17,
    emailAccess: true, banHistory: false, banDetail: '',
    limited: false, limitedDetail: '',
    vpBalance: 0, bpCompleted: 8,
    collections: ['Forsaken', 'Protocol'],
    skinTags: ['Forsaken Vandal', 'Protocol 781-A Phantom'],
    agents: ['Jett','Reyna','Sage','Sova','Killjoy','Omen','Viper','Breach','Phoenix','Skye','Neon','Raze','Chamber','Cypher','Astra','Harbor','Fade'],
    images: [],
    aiSummary: 'Ascendant 2 account (peak Immortal 1) with 35 skins. EU server, email included. Forsaken and Protocol collections. ₹7,200.',
    tags: ['#Ascendant2','#35Skins','#EUServer','#EmailIncluded','#NoBanHistory','#ForsakenCollection','#ProtocolCollection','#ForsakenVandal'],
    accountHistory: 'Played since Episode 4. EU main, moving to Asia.',
    vouchHistory: 'No previous sales',
    createdAt: new Date(Date.now() - 7*24*3600*1000).toISOString(),
    status: 'active', views: 76, contactReveals: 9, saves: 5, isGem: false
  },
  {
    id: 1006, sellerId: 'goldsmithvendor@sample.com', sellerName: 'GoldSmith', sellerRep: 3.5,
    title: 'Gold 3 Starter | 15 Skins | AP | Budget Pick',
    price: 1800, region: 'AP',
    rank: 'Gold 3', peakRank: 'Platinum 1',
    level: 89, skinCount: 15, agentsCount: 10,
    emailAccess: false, banHistory: true, banDetail: '3-day ban in 2022 for AFK in 3 matches. Never restricted since.',
    limited: false, limitedDetail: '',
    vpBalance: 50, bpCompleted: 3,
    collections: ['Glitchpop'],
    skinTags: ['Glitchpop Sheriff', 'Surge Vandal'],
    agents: ['Jett','Reyna','Sage','Omen','Phoenix','Killjoy','Sova','Chamber','Skye','KAY/O'],
    images: [],
    aiSummary: 'Gold 3 account (peak Plat 1) with 15 skins. AP server, credentials only. Previously restricted (AFK, 2022). Budget-friendly at ₹1,800.',
    tags: ['#Gold3','#15Skins','#APServer','#GlitchpopCollection'],
    accountHistory: 'Self-leveled for 1 year. Bought another account, selling this one.',
    vouchHistory: 'No previous sales',
    createdAt: new Date(Date.now() - 12*24*3600*1000).toISOString(),
    status: 'active', views: 45, contactReveals: 6, saves: 2, isGem: false
  }
];
